### ISSUE TITLE
报名HiBlock线下沙龙组织者

### ISSUE THREAD

**Issue by Henry1967** [HiBlock/hiblock#2]
-姓名：张鹏立
-城市：上海
-我的特长是：区块链应用构想
-为什么要申请组织者：学习，寻找合作伙伴

**Comment by bobjiang** [comment]
可以加我微信 hiblocknet
谢谢

**Comment by bobjiang** [comment]
或者给我发邮件：
bob@hiblock.net

上海的活动马上开始
